spring:
  application:
    name: ms-consumer
server:
  port: 8080
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:7961/eureka/
  instance:
    # 将服务的IP地址信息注册到 Eureka上
    prefer-ip-address: true


feign:
  hystrix:
    enabled: true  # 开启服务降级

#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"